
const contract = `{ parameter
    (or (pair %addClaim (pair string bytes) string)
        (pair %removeClaim (pair string bytes) string)) ;
  storage
    (pair (pair (set %claims (pair (pair string bytes) string)) (big_map %metadata string bytes))
          (address %owner)) ;
  code { UNPAIR ;
         IF_LEFT
           { DUP ;
             DUG 2 ;
             CDR ;
             PAIR ;
             SWAP ;
             DUP ;
             DUG 2 ;
             CAR ;
             CDR ;
             DIG 2 ;
             CAR ;
             CAR ;
             DIG 2 ;
             UNPAIR ;
             SWAP ;
             DUP ;
             DUG 2 ;
             CDR ;
             SENDER ;
             COMPARE ;
             NEQ ;
             IF { PUSH string "Unauthorized." ; FAILWITH } {} ;
             SWAP ;
             DUP ;
             DUG 2 ;
             CDR ;
             DIG 2 ;
             DUP ;
             DUG 3 ;
             CAR ;
             CDR ;
             DIG 3 ;
             CAR ;
             CAR ;
             DIG 3 ;
             DIG 5 ;
             DIG 5 ;
             PAIR ;
             PAIR ;
             PUSH bool True ;
             SWAP ;
             UPDATE ;
             PAIR ;
             PAIR ;
             NIL operation ;
             PAIR }
           { DUP ;
             DUG 2 ;
             CDR ;
             PAIR ;
             SWAP ;
             DUP ;
             DUG 2 ;
             CAR ;
             CDR ;
             DIG 2 ;
             CAR ;
             CAR ;
             DIG 2 ;
             UNPAIR ;
             SWAP ;
             DUP ;
             DUG 2 ;
             CDR ;
             SENDER ;
             COMPARE ;
             NEQ ;
             IF { PUSH string "Unauthorized." ; FAILWITH } {} ;
             SWAP ;
             DUP ;
             DUG 2 ;
             CDR ;
             DIG 2 ;
             DUP ;
             DUG 3 ;
             CAR ;
             CDR ;
             DIG 3 ;
             CAR ;
             CAR ;
             DIG 3 ;
             DIG 5 ;
             DIG 5 ;
             PAIR ;
             PAIR ;
             PUSH bool False ;
             SWAP ;
             UPDATE ;
             PAIR ;
             PAIR ;
             NIL operation ;
             PAIR } } }`;

module.exports.contract = contract;
