version: "3.6"
services:
  db:
    container_name: tzkt-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: tzkt-api
    restart: always
    image: bakingbad/tzkt-api:1.6.0
    environment:
      - TZKT_API_KESTREL__ENDPOINTS__HTTP__URL=http://0.0.0.0:5000
    depends_on:
      - db
      - sync
    ports:
      - 5000:5000

  sync:
    container_name: tzkt-sync
    restart: always
    image: bakingbad/tzkt-sync:1.6.0
    environment:
      - TZKT_TEZOSNODE__ENDPOINT=http://sandbox:20000/
      - TZKT_TEZOSNODE__CHAINID=NetXzcB5DmnBoxG
    depends_on:
      - db
      - sandbox

  sandbox:
    container_name: tzkt-sandbox
    restart: always
    image: tqtezos/flextesa:20210602
    command: granabox start
    environment:
      - flextesa_node_cors_origin=*
    ports:
      - 8732:20000

volumes:
  postgres:
