spec_version: 1.2
package: tzprofiles_indexer

database:
  kind: postgres
  host: ${PSQL_HOST:-db}
  port: 5432
  user: dipdup
  password: ${POSTGRES_PASSWORD:-changeme}
  database: dipdup

hasura:
  url: ${HASURA_URL:-http://hasura:8080}
  admin_secret: ${ADMIN_SECRET:-changeme}

contracts:
  tzprofile_old:
    address: KT1KsmdYxuJHCMqLRX1PH7JJeXvXaMeicEa7
    typename: tzprofile
  tzprofile:
    address: KT1G6jaUQkRcxJcnrNLjCTn7xgD686PM2mEd
    typename: tzprofile

datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
    http:
      retry_count: ${HTTP_RETRY_COUNT:-25}
      retry_sleep: ${HTTP_RETRY_SLEEP:-60}
      retry_multiplier: ${HTTP_RETRY_MULTIPLIER:-2}
      ratelimit_rate: ${HTTP_RATELIMIT_RATE:-100}
      ratelimit_period: ${HTTP_RATELIMIT_PERIOD:-1}
      connection_timeout: ${HTTP_CONNECTION_TIMEOUT:-3000}

templates:
  tzprofiles:
    kind: operation
    datasource: tzkt
    contracts:
      - <contract>
    types:
      - transaction
    handlers:
      - callback: on_update
        pattern:
          - destination: <contract>
            entrypoint: default

indexes:
  factory:
    kind: operation
    datasource: tzkt
    types:
      - origination
    handlers:
      - callback: on_factory_origination
        pattern:
          - type: origination
            similar_to: tzprofile
      - callback: on_factory_origination
        pattern:
          - type: origination
            similar_to: tzprofile_old

hooks:
  resolver:
    callback: resolver

jobs:
  resolver:
    hook: resolver
    daemon: True

logging: ${LOG_LEVEL:-quiet}

advanced:
  # sync_limit: 5
  early_realtime: True
  merge_subscriptions: True
  metadata_interface: True
  reindex:
    rollback: ignore

