export { default as Connect } from './Connect/Connect.svelte';
export { default as Ethereum } from './Ethereum.svelte';
export { default as Faq } from './Faq/Faq.svelte';
export { default as GitHub} from './GitHub.svelte';
export { default as Twitter } from './Twitter.svelte';
export { default as Claims } from './Claims.svelte';
export { default as BasicProfile } from './BasicProfile.svelte';
export { default as TermsOfService } from './TermsOfService.svelte';
export { default as PrivacyPolicy } from './PrivacyPolicy.svelte';
export { default as Deploy } from './Deploy.svelte';
export { default as Search } from './Search/Search.svelte';
export { default as Splash } from './Splash/Splash.svelte';
export { default as View } from './View.svelte';
export { default as DiscordVerification } from './DiscordVerification/DiscordVerification.svelte';
export { default as DnsVerification } from './DnsVerification/DnsVerification.svelte';
export * from './context';
