# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel


class Claim(BaseModel):
    bytes: str
    string_0: str
    string_1: str


class TzprofileStorage(BaseModel):
    claims: List[Claim]
    contract_type: str
    metadata: Dict[str, str]
    owner: str
