# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Claim(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    bytes: str
    string_1: str


class TzprofileStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    claims: List[Claim]
    contract_type: str
    metadata: Dict[str, str]
    owner: str
