# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ListItem(BaseModel):
    string_0: str
    bytes: str
    string_1: str


class DefaultParameter(BaseModel):
    list: List[ListItem]
    bool: bool
